---
AllCops:
  Exclude:
    - 'build/**/*'
    - 'pkg/**/*'
    - 'config/software/ncurses.rb'

Style/FileName:
  Enabled: false

Metrics/LineLength:
  Max: 126

Style/SingleSpaceBeforeFirstArg:
  Enabled: false

Style/StringLiterals:
  Enabled: false

# XXX ruby1.8 still used in ci-
Style/HashSyntax:
  Enabled: false
