#!/bin/sh
#

# XXX 11.06.15 these were installed in a previous version, remove after a while
rm -f /usr/local/bin/ruby_devkit
rm -f /usr/local/bin/rake_devkit
rm -f /usr/local/bin/rubocop_devkit
rm -f /usr/local/bin/omnibus_devkit
# XXX end
rm -f /etc/profile.d/devkit.sh
